import { defineScenario } from "./model";

export const HANA_HQ_SCENARIO = defineScenario({
  id: "hana-hq",
  ariaLabel: "HANA HQ Grasshopper 스타일 프로젝트 캔버스",
  world: { width: 12200, height: 2400 },
  initialFocus: { x: 0, y: 1250 },
  nodes: [
    {
      id: "hana-title",
      kind: "scribble",
      text: "HANA HQ",
      ariaLabel: "HANA HQ 프로젝트 제목",
      position: { x: 180, y: 170 },
      size: { width: 940, height: 180 },
      ports: [],
    },
    {
      id: "ref-viewer",
      kind: "viewer",
      viewerType: "model",
      caption: "REFERENCE SURFACE",
      emptyMessage: "RHINO MODEL PLACEHOLDER",
      ariaLabel: "비어 있는 Ref. Surface 모델 뷰어",
      position: { x: 180, y: 720 },
      size: { width: 720, height: 720 },
      ports: [{ id: "model", side: "out", offset: 0.5 }],
    },
    {
      id: "ref-srf",
      kind: "connector",
      text: "Ref. SRF",
      ariaLabel: "Ref. SRF 연결 컴포넌트",
      position: { x: 1100, y: 995 },
      size: { width: 430, height: 170 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "architectural-design",
      kind: "connector",
      text: "Architectural Design",
      ariaLabel: "Architectural Design 가상 연결 컴포넌트",
      position: { x: 1580, y: 1370 },
      size: { width: 480, height: 170 },
      ports: [{ id: "out", side: "out", offset: 0.5 }],
    },
    {
      id: "deconstruct",
      kind: "processor",
      title: "DECONSTRUCT REF. SURFACE",
      icon: "/assets/hana-hq/icons/deconstruct-ref-surface.png",
      ariaLabel: "Deconstruct Ref. Surface 주요 컴포넌트",
      position: { x: 2100, y: 600 },
      size: { width: 760, height: 980 },
      ports: [
        { id: "ref-srf", side: "in", offset: 0.24, label: "Ref. SRF", required: true },
        {
          id: "architectural-design",
          side: "in",
          offset: 0.76,
          label: "Architectural Design",
          required: true,
        },
        { id: "wood-panel", side: "out", offset: 0.14, label: "Wood Panel" },
        { id: "wood-block", side: "out", offset: 0.32, label: "Wood Block" },
        { id: "corner-reveal", side: "out", offset: 0.5, label: "Corner Reveal" },
        { id: "base-board", side: "out", offset: 0.68, label: "Base Board" },
        { id: "t-bar-system", side: "out", offset: 0.86, label: "T-Bar System" },
      ],
    },
    {
      id: "wood-panel",
      kind: "connector",
      text: "Wood Panel",
      ariaLabel: "Wood Panel 연결 컴포넌트",
      position: { x: 3180, y: 662 },
      size: { width: 450, height: 150 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "wood-block",
      kind: "connector",
      text: "Wood Block",
      ariaLabel: "Wood Block 연결 컴포넌트",
      position: { x: 3180, y: 838 },
      size: { width: 450, height: 150 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "corner-reveal",
      kind: "connector",
      text: "Corner Reveal",
      ariaLabel: "Corner Reveal 연결 컴포넌트",
      position: { x: 3180, y: 1015 },
      size: { width: 450, height: 150 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "base-board",
      kind: "connector",
      text: "Base Board",
      ariaLabel: "Base Board 연결 컴포넌트",
      position: { x: 3180, y: 1191 },
      size: { width: 450, height: 150 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "t-bar-system",
      kind: "connector",
      text: "T-Bar System",
      ariaLabel: "T-Bar System 연결 컴포넌트",
      position: { x: 3180, y: 1368 },
      size: { width: 450, height: 150 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "fabrication",
      kind: "processor",
      title: "FABRICATION & CONSTRUCTION REQUIREMENTS",
      icon: "/assets/hana-hq/icons/fabrication-requirements.png",
      ariaLabel: "Fabrication and Construction Requirements 주요 컴포넌트",
      position: { x: 3980, y: 360 },
      size: { width: 860, height: 1120 },
      ports: [
        { id: "wood-panel", side: "in", offset: 0.34, label: "Wood Panel", required: true },
        { id: "finish-method", side: "out", offset: 0.15, label: "Finish Method" },
        {
          id: "fabrication-method",
          side: "out",
          offset: 0.31,
          label: "Fabrication Method",
        },
        {
          id: "panel-thickness",
          side: "out",
          offset: 0.5,
          label: "Panel Thickness (mm)",
        },
        { id: "panel-width", side: "out", offset: 0.63, label: "Panel Width (mm)" },
        { id: "joint-width", side: "out", offset: 0.76, label: "Joint Width (mm)" },
        { id: "max-length", side: "out", offset: 0.89, label: "Max Length (mm)" },
      ],
    },
    {
      id: "finish-method",
      kind: "panel",
      value: "Wood veneer application",
      ariaLabel: "Finish Method 패널: Wood veneer application",
      position: { x: 5200, y: 448 },
      size: { width: 1040, height: 160 },
      ports: [{ id: "in", side: "in", offset: 0.5 }],
    },
    {
      id: "fabrication-method",
      kind: "panel",
      value: "Laminated timber fabrication followed by steam bending",
      ariaLabel: "Fabrication Method 설명 패널",
      position: { x: 5200, y: 650 },
      size: { width: 1180, height: 200 },
      ports: [{ id: "in", side: "in", offset: 0.5 }],
    },
    {
      id: "panel-thickness",
      kind: "panel",
      value: "20",
      ariaLabel: "Panel Thickness 20 millimeters 패널",
      position: { x: 5200, y: 900 },
      size: { width: 390, height: 140 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "panel-width",
      kind: "panel",
      value: "200",
      ariaLabel: "Panel Width 200 millimeters 패널",
      position: { x: 5200, y: 1070 },
      size: { width: 390, height: 140 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "joint-width",
      kind: "panel",
      value: "6",
      ariaLabel: "Joint Width 6 millimeters 패널",
      position: { x: 5200, y: 1240 },
      size: { width: 390, height: 140 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "max-length",
      kind: "panel",
      value: "2400",
      ariaLabel: "Max Length 2400 millimeters 패널",
      position: { x: 5200, y: 1410 },
      size: { width: 390, height: 140 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "construct",
      kind: "processor",
      title: "CONSTRUCT WOOD PANEL 3D",
      icon: "/assets/hana-hq/icons/construct-wood-panel.png",
      ariaLabel: "Construct Wood Panel 3D 주요 컴포넌트",
      position: { x: 6550, y: 650 },
      size: { width: 900, height: 900 },
      ports: [
        { id: "wood-panel", side: "in", offset: 0.18, label: "Wood Panel", required: true },
        {
          id: "panel-thickness",
          side: "in",
          offset: 0.4,
          label: "Panel Thickness (mm)",
          required: true,
        },
        {
          id: "panel-width",
          side: "in",
          offset: 0.55,
          label: "Panel Width (mm)",
          required: true,
        },
        {
          id: "joint-width",
          side: "in",
          offset: 0.7,
          label: "Joint Width (mm)",
          required: true,
        },
        {
          id: "max-length",
          side: "in",
          offset: 0.85,
          label: "Max Length (mm)",
          required: true,
        },
        { id: "model", side: "out", offset: 0.5, label: "3D Model" },
      ],
    },
    {
      id: "model-viewer",
      kind: "viewer",
      viewerType: "model",
      caption: "3D MODEL",
      emptyMessage: "AWAITING 3D MODEL",
      readyMessage: "3D MODEL LINKED",
      readyWhen: ["construct-to-model-viewer"],
      ariaLabel: "비어 있는 3D Model 뷰어",
      position: { x: 7900, y: 760 },
      size: { width: 680, height: 680 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "model-reference",
      kind: "connector",
      text: "3D Model",
      ariaLabel: "3D Model 연결 컴포넌트",
      position: { x: 8870, y: 1015 },
      size: { width: 440, height: 170 },
      ports: [
        { id: "in", side: "in", offset: 0.5 },
        { id: "out", side: "out", offset: 0.5 },
      ],
    },
    {
      id: "generate-drawings",
      kind: "processor",
      title: "GENERATE 2D DRAWINGS",
      icon: "/assets/hana-hq/icons/generate-2d-drawings.png",
      ariaLabel: "Generate 2D Drawings 주요 컴포넌트",
      position: { x: 9900, y: 780 },
      size: { width: 820, height: 720 },
      ports: [
        { id: "model", side: "in", offset: 0.5, label: "3D Model", required: true },
        { id: "drawing", side: "out", offset: 0.5, label: "2D Drawing" },
      ],
    },
    {
      id: "drawing-viewer",
      kind: "viewer",
      viewerType: "image",
      caption: "2D DRAWING",
      emptyMessage: "AWAITING 3D MODEL INPUT",
      readyMessage: "2D DRAWING READY",
      readyWhen: ["model-reference-to-generate"],
      ariaLabel: "비어 있는 2D Drawing 이미지 뷰어",
      position: { x: 11200, y: 760 },
      size: { width: 720, height: 720 },
      ports: [{ id: "in", side: "in", offset: 0.5 }],
    },
  ],
  connections: [
    {
      id: "ref-viewer-to-reference",
      from: { nodeId: "ref-viewer", portId: "model" },
      to: { nodeId: "ref-srf", portId: "in" },
      initiallyConnected: true,
    },
    {
      id: "reference-to-deconstruct",
      from: { nodeId: "ref-srf", portId: "out" },
      to: { nodeId: "deconstruct", portId: "ref-srf" },
      initiallyConnected: false,
      mutable: true,
    },
    {
      id: "architecture-to-deconstruct",
      from: { nodeId: "architectural-design", portId: "out" },
      to: { nodeId: "deconstruct", portId: "architectural-design" },
      initiallyConnected: true,
    },
    ...[
      "wood-panel",
      "wood-block",
      "corner-reveal",
      "base-board",
      "t-bar-system",
    ].map((id) => ({
      id: `deconstruct-to-${id}`,
      from: { nodeId: "deconstruct", portId: id },
      to: { nodeId: id, portId: "in" },
      initiallyConnected: true,
    })),
    {
      id: "wood-panel-to-fabrication",
      from: { nodeId: "wood-panel", portId: "out" },
      to: { nodeId: "fabrication", portId: "wood-panel" },
      initiallyConnected: true,
    },
    ...[
      "finish-method",
      "fabrication-method",
      "panel-thickness",
      "panel-width",
      "joint-width",
      "max-length",
    ].map((id) => ({
      id: `fabrication-to-${id}`,
      from: { nodeId: "fabrication", portId: id },
      to: { nodeId: id, portId: "in" },
      initiallyConnected: true,
    })),
    {
      id: "wood-panel-to-construct",
      from: { nodeId: "wood-panel", portId: "out" },
      to: { nodeId: "construct", portId: "wood-panel" },
      initiallyConnected: false,
      mutable: true,
    },
    ...["panel-thickness", "panel-width", "joint-width", "max-length"].map(
      (id) => ({
        id: `${id}-to-construct`,
        from: { nodeId: id, portId: "out" },
        to: { nodeId: "construct", portId: id },
        initiallyConnected: true,
      }),
    ),
    {
      id: "construct-to-model-viewer",
      from: { nodeId: "construct", portId: "model" },
      to: { nodeId: "model-viewer", portId: "in" },
      initiallyConnected: false,
      mutable: true,
    },
    {
      id: "model-viewer-to-reference",
      from: { nodeId: "model-viewer", portId: "out" },
      to: { nodeId: "model-reference", portId: "in" },
      initiallyConnected: true,
    },
    {
      id: "model-reference-to-generate",
      from: { nodeId: "model-reference", portId: "out" },
      to: { nodeId: "generate-drawings", portId: "model" },
      initiallyConnected: false,
      mutable: true,
    },
    {
      id: "generate-to-drawing-viewer",
      from: { nodeId: "generate-drawings", portId: "drawing" },
      to: { nodeId: "drawing-viewer", portId: "in" },
      initiallyConnected: true,
    },
  ],
});
